### ISSUE TITLE
TypeError: Cannot read property 'uri' of undefined

### ISSUE THREAD

**Issue by mgifford** [aeolingamenfel/lighthouse-crawler#1]
I can't get this to work. On a Mac I do the following:

$ lighthouse-crawler https://openconcept.ca
Beginning site crawl...
/usr/local/lib/node_modules/lighthouse-crawler/core/LighthouseCrawler.js:71
        const url = request.uri.href;
                            ^

TypeError: Cannot read property 'uri' of undefined
    at LighthouseCrawler.pageWasFound (/usr/local/lib/node_modules/lighthouse-crawler/core/LighthouseCrawler.js:71:29)
    at LighthouseCrawler.crawlLoadedPage (/usr/local/lib/node_modules/lighthouse-crawler/core/LighthouseCrawler.js:58:14)
    at Object.callback (/usr/local/lib/node_modules/lighthouse-crawler/core/LighthouseCrawler.js:35:22)
    at Crawler._onContent (/usr/local/lib/node_modules/lighthouse-crawler/node_modules/node-webcrawler/lib/crawler.js:355:21)
    at Request._callback (/usr/local/lib/node_modules/lighthouse-crawler/node_modules/node-webcrawler/lib/crawler.js:328:25)
    at self.callback (/usr/local/lib/node_modules/lighthouse-crawler/node_modules/request/request.js:187:22)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Request.init (/usr/local/lib/node_modules/lighthouse-crawler/node_modules/request/request.js:275:17)
    at new Request (/usr/local

**Comment by ava-cassiopeia** [comment]
Interesting, I'll need to investigate further. I appreciate you reporting this.

**Comment by StrangeWill** [comment]
If I do this to the original code base:

```
    crawlLoadedPage(error, result, $) {
        console.log(error);
        this.pageWasFound(result.request);

```

I end up with the error:

`Error: Invalid URI "/"`

So I'm guessing it's struggling to handle the relative URI path for some reason.
